export const currencies =
[
  { id: 'AUD', name: 'Australian dollar' },
  { id: 'BDT', name: 'Bangladeshi taka' },
  { id: 'BGN', name: 'Bulgarian lev' },
  { id: 'BRL', name: 'Brazilian real' },
  { id: 'BYN', name: 'Belarusian new rouble' },
  { id: 'CAD', name: 'Canadian dollar' },
  { id: 'CHF', name: 'Swiss franc' },
  { id: 'CNY', name: 'Chinese yuan' },
  { id: 'CZK', name: 'Czech koruna' },
  { id: 'DKK', name: 'Danish krone' },
  { id: 'EUR', name: 'Euro' },
  { id: 'GBP', name: 'Pound sterling' },
  { id: 'HKD', name: 'Hong Kong dollar' },
  { id: 'HRK', name: 'Croatian kuna' },
  { id: 'HUF', name: 'Hungarian forint' },
  { id: 'HUF', name: 'Hungarian forint' },
  { id: 'I44', name: 'Import-weighted krone exchange rate' },
  { id: 'IDR', name: 'Indonesian rupiah' },
  { id: 'ILS', name: 'Israeli new shekel' },
  { id: 'INR', name: 'Indian rupee' },
  { id: 'ISK', name: 'Icelandic krona' },
  { id: 'JPY', name: 'Japanese yen' },
  { id: 'KRW', name: 'South Korean won' },
  { id: 'MMK', name: 'Myanmar kyat' },
  { id: 'MXN', name: 'Mexican peso' },
  { id: 'MYR', name: 'Malaysian ringgit' },
  { id: 'NOK', name: 'Norwegian krone' },
  { id: 'NZD', name: 'New Zealand dollar' },
  { id: 'PHP', name: 'Philippine peso' },
  { id: 'PKR', name: 'Pakistani rupee' },
  { id: 'PLN', name: 'Polish zloty' },
  { id: 'RON', name: 'New Romanian leu' },
  { id: 'RUB', name: 'Russian rouble' },
  { id: 'SEK', name: 'Swedish krona' },
  { id: 'SGD', name: 'Singapore dollar' },
  { id: 'THB', name: 'Thai baht' },
  { id: 'TRY', name: 'Turkish lira' },
  { id: 'TWD', name: 'New Taiwan dollar' },
  { id: 'TWI', name: 'Trade-weighted krone exchange rate' },
  { id: 'USD', name: 'US dollar' },
  { id: 'VND', name: 'Vietnamese dong' },
  { id: 'XDR', name: 'IMF, special drawing rights' },
  { id: 'ZAR', name: 'South African rand' }
]
